pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./3-way_merge_concepts.html","Concepts de la fusion 3-voies","Concepts de la fusion 3-voies Une session de fusion vous aide à combiner des groupes séparés de modifications dans une nouvelle version des donnée...",""],
["./archive_files.html","Fichiers archives","Fichiers archives Des archives sont des fichiers, tels que .zip, qui contiennent d&#39;autres fichiers. Beyond Compare les affiche comme des dossiers,...",""],
["./bcclipmain.html","Vue d&#39;ensemble de la Comparaison du Presse-Papiers","Vue d&#39;ensemble de la Comparaison du Presse-Papiers La Comparaison du Presse-Papiers s&#39;exécute en arrière-plan, en gardant une trace chaque fois qu...",""],
["./bcclipoptions.html","Options de Comparaison du Presse-Papiers","Options de Comparaison du Presse-Papiers Ces options contrôlent le comportement de la Comparaison du Presse-Papiers. Exécuter au démarrage de Wind...",""],
["./calling_bc_from_other_applications.html","Appeler Beyond Compare à partir d&#39;autres applications","Appeler Beyond Compare à partir d&#39;autres applications Comme vous vous y attendez, le programme d&#39;installation de Beyond Compare crée des raccourci...",""],
["./commandsbc.html","Commandes communes","Commandes communes Le menu principal change en fonction du type de session qui est active. Toutefois, les commandes listées ci-dessous sont commun...",""],
["./commandsdata.html","Commandes de Comparaison de Tableaux","Commandes de Comparaison de Tableaux Ce qui suit est une description des commandes de Comparaison de Tableaux qui s&#39;ajoutent aux commandes commune...",""],
["./commandsdir.html","Commandes de Comparaison de Dossiers","Commandes de Comparaison de Dossiers Ce qui suit est une description des commandes de Comparaison de Dossiers qui s&#39;ajoutent aux commandes commune...",""],
["./commandsdirmerge.html","Commandes de Fusion de Dossiers","Commandes de Fusion de Dossiers Ce qui suit est une description des commandes de Fusion de Dossiers qui s&#39;ajoutent aux commandes communes . La plu...",""],
["./commandsdirsync.html","Commandes de Synchronisation de Dossiers","Commandes de Synchronisation de Dossiers Ce qui suit est une description des commandes de Synchronisation de Dossiers qui s&#39;ajoutent aux commandes...",""],
["./commandshex.html","Commandes de Comparaison Hexadécimale","Commandes de Comparaison Hexadécimale Ce qui suit est une description des commandes de Comparaison Hexadécimale qui s&#39;ajoutent aux commandes commu...",""],
["./commandshome.html","Commandes d&#39;Accueil","Commandes d&#39;Accueil Ce qui suit est une description des commandes de l&#39; Accueil qui s&#39;ajoutent aux commandes communes . Sélectionnez Outils Option...",""],
["./commandsmp3.html","Commandes de Comparaison de MP3","Commandes de Comparaison de MP3 Ce qui suit est une description des commandes de Comparaison de MP3 qui s&#39;ajoutent aux commandes communes . La plu...",""],
["./commandspix.html","Commandes de Comparaison d&#39;Images","Commandes de Comparaison d&#39;Images Ce qui suit est une description des commandes de Comparaison d&#39;Images qui s&#39;ajoutent aux commandes communes . La...",""],
["./commandsreg.html","Commandes de Comparaison de Registres","Commandes de Comparaison de Registres Ce qui suit est une description des commandes de Comparaison de Registres qui s&#39;ajoutent aux commandes commu...",""],
["./commandstext.html","Commandes de Comparaison de Textes","Commandes de Comparaison de Textes Ce qui suit est une description des commandes de Comparaison de Textes qui s&#39;ajoutent aux commandes communes . ...",""],
["./commandstextedit.html","Commandes d&#39;Édition de texte","Commandes d&#39;Édition de texte Ce qui suit est une description des commandes d&#39; Éditeur de texte qui s&#39;ajoutent aux commandes communes . La plupart ...",""],
["./commandstextmerge.html","Commandes de Fusion de Textes","Commandes de Fusion de Textes Ce qui suit est une description des commandes de Fusion de Textes qui s&#39;ajoutent aux commandes communes . La plupart...",""],
["./commandstextpatch.html","Commandes de patch texte","Commandes de patch texte Ce qui suit est une description des commandes de Patch de texte qui s&#39;ajoutent aux commandes communes . La plupart de ces...",""],
["./commandsver.html","Commandes de Comparaison de Versions","Commandes de Comparaison de Versions Ce qui suit est une description des commandes de Comparaison de Versions en plus des commandes communes . La ...",""],
["./commands_reference.html","Référence des commandes","Référence des commandes Cette partie de la documentation décrit les commandes disponibles dans les menus et sur les barres d&#39;outils pour chaque ty...",""],
["./command_line_reference.html","Référence de ligne de commande","Référence de ligne de commande Fichiers exécutables pour une ligne de commande Exécutable Signification BCompare.exe bcompare C&#39;est l&#39;application ...",""],
["./dir_filtering_the_view.html","Filtrage de l&#39;affichage de Comparaison de Dossiers","Filtrage de l&#39;affichage de Comparaison de Dossiers Il y a trois types globaux de filtres que vous pouvez utiliser pour contrôler l&#39;étendue de la s...",""],
["./dir_how_to_compare.html","Comment comparer dans la Comparaison de Dossiers","Comment comparer dans la vue de Comparaison de Dossiers Il y a plusieurs façons de comparer des dossiers et des fichiers. Si vous voulez une vue r...",""],
["./dir_merge_understanding_the_display.html","Comprendre l&#39;affichage de la Fusion de Dossiers","Comprendre l&#39;affichage de la Fusion de Dossiers L&#39;affichage de Fusion de Dossiers utilise des signaux de couleur pour mettre en évidence les diffé...",""],
["./dir_reconciling_differences.html","Réconciliation des différences dans une Comparaison de Dossiers","Réconciliation des différences dans une vue de Comparaison de Dossiers Une session de Comparaison de Dossiers propose des commandes telles que Cop...",""],
["./dir_sync_how_to_sync.html","Comment synchroniser dans la Synchronisation de Dossiers","Comment synchroniser dans la vue de Synchronisation de Dossiers Paramètres de définition de synchronisation Dans la partie supérieure de la vue, s...",""],
["./dir_sync_understanding_the_display.html","Comprendre l&#39;affichage de la Synchronisation de Dossiers","Comprendre l&#39;affichage de la Synchronisation de Dossiers Actions de synchronisation Le fichier de droite sera copié à gauche Le fichier de gauche ...",""],
["./dir_understanding_the_display.html","Comprendre l&#39;affichage de Comparaison de Dossiers","Comprendre l&#39;affichage de Comparaison de Dossiers L&#39;affichage de Comparaison de Dossiers utilise des signaux de couleur pour mettre en évidence le...",""],
["./display_filters.html","Filtres d&#39;affichage","Filtres d&#39;affichage Les filtres d&#39;affichage limitent la visualisation à certains résultats de comparaison. Par exemple, vous pouvez sélectionner A...",""],
["./dlgbrowsemachine.html","Sélection d&#39;une base de registre distante","Sélection d&#39;une base de registre distante Si l&#39;ordinateur distant auquel vous voulez vous connecter n&#39;apparaît pas dans la liste, vous pouvez avoi...",""],
["./dlgdatacolhandling.html","Modifier une définition de colonne","Modifier une définition de colonne Le dialogue Traitement de colonne vous permet de définir les options pour chaque colonne de comparaison. Un sou...",""],
["./dlgdiralignwithitem.html","Modifier une substitution d&#39;alignement","Modifier une substitution d&#39;alignement Remplissez les champs Aligner le fichier (ou le dossier) de gauche et Aligner le fichier (ou le dossier) de...",""],
["./dlgdirfind.html","Recherche de noms de fichier","Recherche de noms de fichier Recherche Rechercher un nom de fichier Pour localiser un fichier spécifique dans une vue de dossier, sélectionnez Rec...",""],
["./dlgdirotherfilteritem.html","Modifier un élément Autre filtre","Modifier un élément Autre filtre Pour filtrer par date 1.Sélectionnez Plus anciens que ou Plus récents que. 2.Si Jour(s) avant est coché, ce filtr...",""],
["./dlgexport.html","Paramètres d&#39;exportation","Paramètres d&#39;exportation Outils Exporter les paramètres Vous pouvez enregistrer sélectivement vos paramètres du programme pour les transférer vers...",""],
["./dlgfileformatmanager.html","Gestion des formats de fichier","Gestion des formats de fichier Outils Formats de fichier Sélectionnez Outils Formats de fichier pour voir et gérer la liste entière des formats de...",""],
["./dlgimport.html","Importation des paramètres","Importation des paramètres Outils Importer les paramètres Vous pouvez importer des paramètres que vous avez précédemment exportés de Beyond Compar...",""],
["./dlgnag.html","Comment s&#39;enregistrer","Comment s&#39;enregistrer Étape 1 - Essayez-le Vous pouvez utiliser le programme pendant 30 jours pour voir s&#39;il convient à vos besoins. Si vous l&#39;uti...",""],
["./dlgopenwithitem.html","Modifier un élément Ouvrir avec","Modifier un élément Ouvrir avec Entrez un nom dans le champ Description pour qu&#39;il apparaisse dans le menu Ouvrir avec. Pour définir un raccourci ...",""],
["./dlgprofilebrowse.html","Parcourir en utilisant des profils","Parcourir en utilisant des profils Session Rechercher un dossier En général, lorsque des répertoires peuvent être utilisés dans Beyond Compare, de...",""],
["./dlgprofilemanager.html","Gestion de profil","Gestion de profil Outils Profils Sélectionnez Outils Profils pour voir et gérer la liste entière des profils. En plus des profils nommés, il y a l...",""],
["./dlgprogoptions.html","Options du programme","Options du programme Outils Options Pour définir les préférences du programme 1.Sélectionnez Outils Options pour ouvrir le dialogue Options. 2.Dan...",""],
["./dlgregister.html","Comment déverrouiller Beyond Compare","Comment déverrouiller Beyond Compare Aide Entrer la clé Beyond Compare est distribué en mode évaluation, cela vous permet de voir s&#39;il répond à vo...",""],
["./dlgreport.html","Rapports","Rapports Les rapports de comparaison vous permettent d&#39;enregistrer les informations d&#39;une comparaison pour la visualiser plus tard sans devoir ré-...",""],
["./dlgrestore.html","Restauration des défauts usine","Restauration des défauts usine Outils Restaurer les défauts usine Vous pouvez restaurer les paramètres à leurs valeurs par défaut usine. Pour rest...",""],
["./dlgsnapshot.html","Enregistrement d&#39;Instantanés","Enregistrement d&#39;Instantanés Outils Enregistrer un Instantané Pour enregistrer un Instantané 1.Sélectionnez Outils Enregistrer un Instantané . 2.E...",""],
["./dlgsourcecontrolmanager.html","Intégration de contrôle de source","Intégration de contrôle de source Outils Intégration de contrôle de source Vous pouvez associer des dossiers avec une application de contrôle de s...",""],
["./dlgsupport.html","Rapporter des problèmes","Rapporter des problèmes Aide Support Si vous avez découvert un problème avec Beyond Compare, nous souhaiterions que vous nous en parliez ! À parti...",""],
["./dlgtextfindinfiles.html","Recherche de texte dans des fichiers","Recherche de texte dans des fichiers Recherche Rechercher dans des fichiers Pour localiser du texte spécifique dans plusieurs fichiers, sélectionn...",""],
["./dlgtextgrammaritem.html","Modifier un élément de grammaire","Modifier un élément de grammaire Sélectionnez un Nom d&#39;élément existant dans la liste déroulante ou entrer votre propre nouveau nom. Pour définir ...",""],
["./dlgtextreplacementitem.html","Modifier un élément texte de remplacement","Modifier un élément texte de remplacement Spécifiez le Texte à rechercher et le texte Remplacer avec. Cochez Respecter la casse de caractère pour ...",""],
["./dlgworkspacemanager.html","Gestion des espaces de travail","Gestion des espaces de travail Session Charger un espace de travail Gérer les espaces de travail Pour enregistrer la configuration de votre espace...",""],
["./editing_text.html","Édition de texte","Édition de texte Chaque panneau de la vue de Comparaison de Textes est un éditeur de texte plein de fonctionnalités. Vous pouvez entrer et modifie...",""],
["./file_formats.html","Formats de fichier","Formats de fichier Beyond Compare utilise des formats de fichier pour spécifier comment certains types de fichiers doivent être traités. Par exemp...",""],
["./file_masks.html","Masques de fichier","Masques de fichier Un masque de fichier est une séquence de caractères \"normaux\" et de caractères génériques utilisée pour faire correspondre des ...",""],
["./formatdata.html","Paramètres de format de tableaux","Paramètres de format de tableaux Les formats de tableaux sont des formats de fichiers utilisés par le type de session Comparaison de Tableaux . Cl...",""],
["./formatdataconversion.html","Paramètres de conversion de Comparaison de Tableaux","Paramètres de conversion de Comparaison de Tableaux Format tableau Conversion L&#39;onglet Conversion définit comment les fichiers sont chargés et enr...",""],
["./formatdatageneral.html","Paramètres généraux de format de tableaux","Paramètres généraux de format de tableaux Format tableau Général Le Masque est un ensemble de types de fichier à associer avec ce format de fichie...",""],
["./formatdataregional.html","Paramètres régionaux de format de tableaux","Paramètres régionaux de format de tableaux Format tableau Régional Cochez Utiliser le système pour utiliser les Paramètres régionaux de votre syst...",""],
["./formatdatatype.html","Paramètres de type de format de tableaux","Paramètres de type de format de tableaux Format tableau Type L&#39;onglet Type définit la syntaxe du fichier de données. Fichiers texte délimités Séle...",""],
["./formatexternalgeneral.html","Paramètres généraux de format externe","Paramètres généraux de format externe Format externe Général Pour comparer des fichiers avec une autre application, définissez un format externe. ...",""],
["./formathex.html","Paramètres de Format hexadécimal","Paramètres de Format hexadécimal Les formats hexadécimaux sont des formats de fichier utilisés par le type de session Comparaison Hexadécimale . C...",""],
["./formathexconversion.html","Paramètres de conversion de Format hexadécimal","Paramètres de conversion de Format hexadécimal Format hexadécimal Conversion L&#39;onglet Conversion définit comment les fichiers sont chargés et enre...",""],
["./formathexgeneral.html","Paramètres généraux de Comparaison Hexadécimale","Paramètres généraux de Comparaison Hexadécimale Format hexadécimal Général Le Masque est un ensemble de types de fichier à associer avec ce format...",""],
["./formatpix.html","Paramètres de format d&#39;images","Paramètres de format d&#39;images Les formats d&#39;image sont des formats de fichier utilisés par une session type de Comparaison d&#39;Images . Cliquez sur ...",""],
["./formatpixconversion.html","Paramètres de conversion de format d&#39;image","Paramètres de conversion de format d&#39;image Format image Conversion L&#39;onglet Conversion définit comment les fichiers sont chargés. Sélectionnez une...",""],
["./formatpixgeneral.html","Paramètres généraux de format d&#39;image","Paramètres généraux de format d&#39;image Format image Général Le Masque est un ensemble de types de fichier à associer avec ce format de fichier. La ...",""],
["./formattext.html","Paramètres de format de texte","Paramètres de format de texte Les formats de texte sont des formats de fichier utilisés par les types de session Comparaison de Textes et Fusion d...",""],
["./formattextconversion.html","Paramètres de conversion de format de texte","Paramètres de conversion de format de texte Format texte Conversion L&#39;onglet Conversion définit comment les fichiers sont chargés et enregistrés. ...",""],
["./formattextgeneral.html","Paramètres généraux de format de texte","Paramètres généraux de format de texte Format texte Général Le Masque est un ensemble de types de fichier à associer avec ce format de fichier. La...",""],
["./formattextgrammar.html","Paramètres de grammaire de format de texte","Paramètres de grammaire de format de texte Format texte Grammaire L&#39;onglet Grammaire définit la syntaxe d&#39;un fichier. Les éléments de grammaire te...",""],
["./formattextmisc.html","Paramètres divers de format de texte","Paramètres divers de format de texte Format texte Divers Insérer des espaces au lieu de tabulations Quand décoché, appuyer sur la touche Tab insèr...",""],
["./glossary.html","Glossaire","Glossaire Dossier de base Le dossier le plus au-dessus de chaque côté d&#39;une vue de dossiers. Les noms des dossiers de base apparaissent dans la zo...",""],
["./grammars.html","Grammaires","Grammaires Une spécification de format de fichier peut inclure une définition de grammaire utilisée pour le surlignage syntaxique et pour aider à ...",""],
["./license_agreement.html","Contrat de Licence","Contrat de Licence Aide À propos de Beyond Compare Licence Votre utilisation de Beyond Compare est régie par les Clauses et Conditions suivantes :...",""],
["./license_agreement_7-zip.html","License Agreement: 7-Zip","7-Zip License for use and distribution 7-Zip Copyright (C) 1999-2010 Igor Pavlov. Licenses for files are: 1) 7z.dll: GNU LGPL + unRAR restriction ...",""],
["./license_agreement_fpc.html","License Agreement: FPC","FPC LICENSE This is the file COPYING.FPC, it applies to the Free Pascal Run-Time Library (RTL) and packages (packages) distributed by members of t...",""],
["./license_agreement_gpl3.html","License Agreement: GPL3","GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007 Copyright &#169; 2007 Free Software Foundation, Inc. Everyone is permitted to copy and distribute ve...",""],
["./license_agreement_htmlviewer.html","License Agreement: HtmlViewer","HtmlViewer License Copyright (c) 1995 - 2008 by L. David Baldwin Copyright (c) 1995 - 2008 by Anders Melander (DitherUnit.pas) Copyright (c) 1995 ...",""],
["./license_agreement_httpget.html","License Agreement: HTTPGet","HTTPGet License This software is provided &#39;as-is&#39;, without any express or implied warranty. In no event will the author be held liable for any dam...",""],
["./license_agreement_innosetup.html","License Agreement: InnoSetup","Inno Setup License Except where otherwise noted, all of the documentation and software included in the Inno Setup package is copyrighted by Jordan...",""],
["./license_agreement_intlck64.html","License Agreement: IntLck64","IntLck64 License Copyright (C) 2005 Will DeWitt Jr. This software is provided &#39;as-is&#39;, without any express or implied warranty. In no event will t...",""],
["./license_agreement_lgpl.html","License Agreement: LGPL","GNU LIBRARY GENERAL PUBLIC LICENSE Version 2, June 1991 Copyright (C) 1991 Free Software Foundation, Inc. 51 Franklin St, Fifth Floor, Boston, MA ...",""],
["./license_agreement_mpl.html","License Agreement: MPL","Mozilla Public License Version 2.0 1. Definitions 1.1. \"Contributor\" means each individual or legal entity that creates, contributes to the creati...",""],
["./license_agreement_pcre.html","License Agreement: PCRE","PCRE License PCRE is a library of functions to support regular expressions whose syntax and semantics are as close as possible to those of the Per...",""],
["./license_agreement_regexpr.html","License Agreement: RegExpr","RegExpr License Author: Andrey V. Sorokin St-Petersburg Russia anso@mail.ru , anso@usa.net http://anso.da.ru http://anso.virtualave.net This libra...",""],
["./license_agreement_textdiff.html","License Agreement: TextDiff","TextDiff License Author: Angus Johnson - angusj-AT-myrealbox-DOT-com Copyright: &#169; 2001-2005 Angus Johnson Licence to use, terms and conditions The...",""],
["./license_agreement_wavpack.html","License Agreement: WavPack","WavPack License Copyright (c) 1998 - 2009 Conifer Software All rights reserved. Redistribution and use in source and binary forms, with or without...",""],
["./license_agreement_wix.html","License Agreement: WiX","WiX License Copyright (c) 2004, Outercurve Foundation. This software is released under the Microsoft Reciprocal License (MS-RL) (the \"License\"); y...",""],
["./license_agreement_zlib.html","License Agreement: Zlib","Zlib License zlib.h -- interface of the &#39;zlib&#39; general purpose compression library version 1.2.3, July 18th, 2005 Copyright (C) 1995-2005 Jean-lou...",""],
["./managing_sessions.html","Gestion des sessions","Gestion des sessions Beyond Compare enregistre automatiquement les sessions les plus récentes de telle façon que vous pouvez y revenir facilement....",""],
["./moving_bc_to_another_computer.html","Migrer Beyond Compare vers un autre ordinateur","Migrer Beyond Compare vers un autre ordinateur Pour copier ou déplacer Beyond Compare vers un ordinateur différent 1.Sur le nouvel ordinateur, tél...",""],
["./opattrib.html","Attributs","Attributs Actions Attributs Dans le menu Actions, la commande Attributs modifie divers attributs du système d&#39;exploitation des fichiers et dossier...",""],
["./opcompare.html","Comparaisons de contenu","Comparaisons de contenu Actions Comparer les contenus Dans le menu Actions, la commande Comparer les contenus exécute des comparaisons de contenu ...",""],
["./opcopy.html","Copier","Copier Actions Copier vers la droite / Copier vers la gauche / Copier vers un côté Dans le menu Actions, les commandes Copier vers la droite, Copi...",""],
["./opcopyto.html","Copier vers un dossier","Copier vers un dossier Actions Copier vers un dossier Dans le menu Actions, la commande Copier vers un dossier copie les fichiers et les dossiers ...",""],
["./opcopytooutput.html","Copier vers la sortie","Copier vers la sortie Actions Copier vers la sortie Dans le menu Actions, la commande Copier vers la sortie copie les fichiers et les dossiers sél...",""],
["./opdelete.html","Supprimer","Supprimer Actions Supprimer Dans le menu Actions, la commande Supprimer supprime les fichiers et les dossiers sélectionnés pour un ou pour les deu...",""],
["./opexchange.html","Échanger","Échanger Actions Échanger Dans le menu Actions, la commande Échanger déplace les fichiers et dossiers sélectionnés d&#39;un côté d&#39;une vue vers l&#39;autr...",""],
["./opexclude.html","Exclure","Exclure Actions Exclure Dans le menu Actions, la commande Exclure filtre en enlevant les fichiers et dossiers sélectionnés de la session active. U...",""],
["./opmerge.html","Fusionner","Fusionner Actions Fusionner Dans le menu Actions, la commande Fusionner réalise la fusion des fichiers et des dossiers sélectionnés. Si un dossier...",""],
["./opmove.html","Déplacer","Déplacer Actions Déplacer vers la droite / Déplacer vers la gauche / Déplacer vers un côté Dans le menu Actions, les commandes Déplacer vers la dr...",""],
["./opmoveto.html","Déplacer vers un dossier","Déplacer vers un dossier Actions Déplacer vers un dossier Dans le menu Actions, la commande Déplacer vers un dossier déplace les fichiers et les d...",""],
["./opnewfolder.html","Nouveau dossier","Nouveau dossier Actions Nouveau dossier Dans le menu Actions, la commande Nouveau dossier vous permet de créer un dossier à la position actuelle. ...",""],
["./oprename.html","Renommer","Renommer Actions Renommer Dans le menu Actions, la commande Renommer renomme les fichiers et les dossiers sélectionnés. Dans la sous-section Actio...",""],
["./opsync.html","Synchroniser","Synchroniser Actions Synchroniser Mettre à jour à droite / Mettre à jour à gauche / Mettre à jour les deux / Miroir vers la droite / Miroir vers l...",""],
["./optionsarchive.html","Options de type d&#39;archive","Options de type d&#39;archive Outils Options Types d&#39;archive Spécifiez les types de fichier qui doivent être associés avec chacun des formats d&#39;archiv...",""],
["./optionsbackup.html","Options de sauvegarde","Options de sauvegarde Outils Options Sauvegardes Beyond Compare peut créer une sauvegarde de vos fichiers avant de les écraser lors d&#39;une opératio...",""],
["./optionscolor.html","Options de couleur et de fonte","Options de couleur et de fonte Outils Options Couleurs, Fontes Cliquez sur l&#39;élément contenant les options que vous voulez définir : Vues Dossiers...",""],
["./optionscommand.html","Options de Barre d&#39;outils, Raccourcis, Menus","Options de Barre d&#39;outils, Raccourcis, Menus Outils Options Barre d&#39;outils, etc. Ces options vous permettent de contrôler quelles commandes appara...",""],
["./optionsdircolor.html","Options de couleur et de fontes sur la vue Dossiers","Options de couleur et de fontes sur la vue Dossiers Outils Options Couleurs, Fontes Vues Dossiers Ces options vous permettent de personnaliser l&#39;e...",""],
["./optionsfilecolor.html","Options de couleur et de fontes de la vue Fichiers","Options de couleur et de fontes de la vue Fichiers Outils Options Couleurs, Fontes Vues Fichiers Ces options vous permettent de personnaliser les ...",""],
["./optionsnextdiff.html","Options de différence suivante","Options de différence suivante Outils Options Différence suivante Définir ces options pour refléter vos préférences concernant comment dépouiller ...",""],
["./optionsop.html","Options d&#39;opération sur fichier","Options d&#39;opération sur fichier Outils Options Opérations sur fichier Confirmations Par défaut, Beyond Compare demande une confirmation avant d&#39;ex...",""],
["./optionsopenwith.html","Options de l&#39;application \"Ouvrir avec\"","Options de l&#39;application \"Ouvrir avec\" Outils Options Ouvrir avec Vous pouvez configurer des applications externes pour qu&#39;elles apparaissent dans...",""],
["./optionspixcolor.html","Options de couleurs de Comparaison d&#39;Images","Options de couleurs de Comparaison d&#39;Images Outils Options Couleurs, Fontes Comparaison d&#39;Images Ces options vous permettent de personnaliser les ...",""],
["./optionsstartup.html","Options de démarrage","Options de démarrage Outils Options Démarrage Options de démarrage Lorsque Beyond Compare démarre, il affiche normalement la vue Accueil. Pour que...",""],
["./optionstab.html","Options des onglets","Options des onglets Outils Options Onglets Lorsque vous travaillez simultanément avec de multiples sessions, Beyond Compare peut les ouvrir dans d...",""],
["./optionstext.html","Options de modification de texte","Options de modification de texte Outils Options Modification de texte Ces options s&#39;appliquent aux sessions de Comparaison de Textes et de Fusion ...",""],
["./optionstweak.html","Options pour les astuces","Options pour les astuces Outils Options Astuces Les astuces sont des options avancées ou obscures du programme que nous regroupons ici pour éviter...",""],
["./optouch.html","Horodater","Horodater Actions Horodater Dans le menu Actions, la commande Horodater modifie l&#39;horodatage (date/heure de dernière modification) des fichiers sé...",""],
["./pix_how_to_compare.html","Comment comparer dans la Comparaison d&#39;Images","Comment comparer dans la vue de Comparaison d&#39;Images Alignement du contenu de l&#39;image Vous pouvez comparer des images qui ont été retaillées, pivo...",""],
["./profileamazons3.html","Paramètres de profil Amazon S3","Paramètres de profil Amazon S3 Profil S3 d&#39;Amazon Général Type d&#39;authentification Contrôle d&#39;où viennent les informations d&#39;identification. Inform...",""],
["./profiledropbox.html","Paramètres de profil Dropbox","Paramètres de profil Dropbox Profil Dropbox Général La Description peut inclure n&#39;importe quel texte que vous souhaitez. ",""],
["./profileftp.html","Paramètres de connexion de profil FTP","Paramètres de connexion de profil FTP Cliquez sur l&#39;onglet pour les paramètres que vous voulez modifier : Global Identification Serveur Connexion ...",""],
["./profileftpconnection.html","Paramètres de connexion de profil FTP","Paramètres de connexion de profil FTP Profil FTP Connexion Ces paramètres contrôlent comment la connexion vers le serveur distant est réalisée. Co...",""],
["./profileftpglobal.html","Paramètres globaux de profil FTP","Paramètres globaux de profil FTP Profil FTP par défaut Global Connexions anonymes Adresse courriel Lors de connexion à des sites FTP anonymes, il ...",""],
["./profileftplisting.html","Paramètres de liste de profil FTP","Paramètres de liste de profil FTP Profil FTP Rapports Beyond Compare analyse les listes de répertoire en texte brut envoyées par le serveur FTP en...",""],
["./profileftplogin.html","Paramètres de connexion de profil FTP","Paramètres de connexion de profil FTP Profil FTP Identification Protocole Spécifiez FTP ou une des options FTP sécurisé : SSL ou SSH. Port Écrasez...",""],
["./profileftpproxy.html","Paramètres de proxy de profil FTP","Paramètres de proxy de profil FTP Profil FTP Proxy Utiliser un proxy Cochez si les connexions doivent utiliser le protocole FTP Proxy. Si vous n&#39;ê...",""],
["./profileftpserver.html","Paramètres de serveur de profil FTP","Paramètres de serveur de profil FTP Profil FTP Serveur Les noms de fichier sont sensibles à la casse Cochez pour que la casse des caractères des n...",""],
["./profileftptransfer.html","Paramètres de transfert de profil FTP","Paramètres de transfert de profil FTP Profil FTP Transférer Ces paramètres contrôlent comment des fichiers sont transférés vers et à partir du ser...",""],
["./profileonedrive.html","Paramètres de profil OneDrive","Paramètres de profil OneDrive Profil OneDrive Général La Description peut inclure n&#39;importe quel texte que vous souhaitez. ",""],
["./profilesvn.html","Paramètres de profil Subversion","Paramètres de profil Subversion Profil Subversion Général URL du dépôt, Révision Spécifier des paramètres pour votre compte. La Description peut i...",""],
["./profilewebdav.html","Paramètres de profil WebDAV","Paramètres de profil WebDAV Profil WebDAV Général URL, Nom d&#39;utilisateur, Mot de passe, Listes récursives Spécifier des paramètres pour votre comp...",""],
["./regular_expression_reference.html","Référence d&#39;Expression régulière","Référence d&#39;Expression régulière Les expressions régulières sont une manière puissante de définir des modèles de recherche et d&#39;appariement. Beyon...",""],
["./remote_services.html","Services distants","Services distants Les services distants incluent le FTP et Subversion. Les sites FTP sont représentés en utilisant la syntaxe standard : ftp://Nom...",""],
["./rules_vs_file_formats.html","Règles vs. Formats de fichier","Règles vs. Formats de fichier Dans Beyond Compare, les formats de fichier décrivent la syntaxe des natures spécifiques de fichier en définissant d...",""],
["./sample_regular_expressions.html","Exemples d&#39;expressions régulières","Exemples d&#39;expressions régulières Expression Signification ^abc Représente \"abc\" en début de ligne abc$ Représente \"abc\" en fin de ligne ^abc$ Rep...",""],
["./sample_scripts.html","Exemples de scripts","Exemples de scripts Voici quelques exemples de scripts pour montrer comment Beyond Compare peut utiliser des scripts. Vous pouvez utiliser ces scr...",""],
["./scheduling_a_script.html","Planifier un script","Planifier un script Vous pouvez utiliser le processeur de script de Beyond Compare pour exécuter certaines tâches, telle que la synchronisation de...",""],
["./scripting_reference.html","Référence de script","Référence de script Un script est un fichier texte simple contenant une liste de commandes qui peuvent contrôler le programme et exécuter automati...",""],
["./scripts.html","Scripts","Scripts Beyond Compare fournit une fonctionnalité de traitement par script qui vous permet d&#39;automatiser des tâches routinières. Un script est un ...",""],
["./searching_for_text.html","Rechercher du texte","Rechercher du texte Pour rechercher du texte dans une session de Comparaison de Textes, sélectionnez Rechercher Recherche . Entrez le texte ou un ...",""],
["./sessiondata.html","Paramètres de Comparaison de Tableaux","Paramètres de Comparaison de Tableaux Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spéci...",""],
["./sessiondataalignment.html","Paramètres d&#39;alignement de Comparaison de Tableaux","Paramètres d&#39;alignement de Comparaison de Tableaux Session Paramètres de session Alignement Les paramètres de l&#39;onglet Alignement contrôle l&#39;algor...",""],
["./sessiondatacolumns.html","Paramètres de colonne de Comparaison de Tableaux","Paramètres de colonne de Comparaison de Tableaux Session Paramètres de session Colonnes Chaque ligne de l&#39;affichage représente une colonne de comp...",""],
["./sessiondataformats.html","Paramètres de format de fichier de Comparaison de Tableaux","Paramètres de format de fichier de Comparaison de Tableaux Session Paramètres de session Format Spécifiez le format de fichier à utiliser en lisan...",""],
["./sessiondataspecs.html","Paramètres de spécification d&#39;une Comparaison de Tableaux","Paramètres de spécification d&#39;une Comparaison de Tableaux Session Paramètres de session Spécification Spécifiez les fichiers à comparer. Cochez Dé...",""],
["./sessiondir.html","Paramètres de Comparaison de Dossiers","Paramètres de Comparaison de Dossiers Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spéci...",""],
["./sessiondircomparison.html","Paramètres de comparaison de la Comparaison de Dossiers","Paramètres de comparaison de la Comparaison de Dossiers Session Paramètres de session Comparaison Ces paramètres contrôlent ce qui doit être consi...",""],
["./sessiondirhandling.html","Paramètres de traitement de la Comparaison de Dossiers","Paramètres de traitement de la Comparaison de Dossiers Session Paramètres de session Traitement Traitement de dossier Balayer automatiquement les ...",""],
["./sessiondirmerge.html","Paramètres de Fusion de Dossiers","Paramètres de Fusion de Dossiers Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spécificat...",""],
["./sessiondirmergecomparison.html","Paramètres de comparaison de la Fusion de Dossiers","Paramètres de comparaison de la Fusion de Dossiers Session Paramètres de session Comparaison Ces paramètres contrôlent ce qui doit être considéré ...",""],
["./sessiondirmergehandling.html","Paramètres de traitement de la Fusion de Dossiers","Paramètres de traitement de la Fusion de Dossiers Session Paramètres de session Traitement Traitement de dossier Balayer automatiquement les sous-...",""],
["./sessiondirmergemisc.html","Paramètres divers de la Fusion de Dossiers","Paramètres divers de la Fusion de Dossiers Session Paramètres de session Divers Pour substituer des associations de format de fichier La liste For...",""],
["./sessiondirmergenamefilter.html","Paramètres de filtre de nom de la Fusion de Dossiers","Paramètres de filtre de nom de la Fusion de Dossiers Session Paramètres de session Filtres sur le nom Vous pouvez inclure ou exclure des dossiers ...",""],
["./sessiondirmergeotherfilters.html","Paramètres des autres filtres de la Fusion de Dossiers","Paramètres des autres filtres de la Fusion de Dossiers Session Paramètres de session Autres filtres Vous pouvez exclure des fichiers d&#39;une session...",""],
["./sessiondirmergespecs.html","Paramètres de spécification d&#39;une Fusion de Dossiers","Paramètres de spécification d&#39;une Fusion de Dossiers Session Paramètres de session Spécification Spécifiez les dossiers de base à fusionner. Fusio...",""],
["./sessiondirmisc.html","Paramètres divers de Comparaison de Dossiers","Paramètres divers de Comparaison de Dossiers Session Paramètres de session Divers Pour forcer un alignement différent Par défaut, une session de d...",""],
["./sessiondirnamefilter.html","Paramètres de filtre de nom de la Comparaison de Dossiers","Paramètres de filtre de nom de la Comparaison de Dossiers Session Paramètres de session Filtres sur le nom Vous pouvez inclure ou exclure des doss...",""],
["./sessiondirotherfilters.html","Paramètres des autres filtres de la Comparaison de Dossiers","Paramètres des autres filtres de la Comparaison de Dossiers Session Paramètres de session Autres filtres Vous pouvez exclure des fichiers d&#39;une se...",""],
["./sessiondirspecs.html","Paramètres de spécification d&#39;une Comparaison de Dossiers","Paramètres de spécification d&#39;une Comparaison de Dossiers Session Paramètres de session Spécification Spécifiez les dossiers de base à comparer. C...",""],
["./sessiondirsync.html","Paramètres de Synchronisation de Dossiers","Paramètres de Synchronisation de Dossiers Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : S...",""],
["./sessiondirsynccomparison.html","Paramètres de comparaison de Synchronisation de Dossiers","Paramètres de comparaison de Synchronisation de Dossiers Session Paramètres de session Comparaison Ces paramètres contrôlent ce qui doit être cons...",""],
["./sessiondirsynchandling.html","Paramètres de traitement de la Synchronisation de Dossiers","Paramètres de traitement de la Synchronisation de Dossiers Session Paramètres de session Traitement Traitement de dossier Synchroniser les dossier...",""],
["./sessiondirsyncmisc.html","Paramètres divers de Synchronisation de Dossiers","Paramètres divers de Synchronisation de Dossiers Session Paramètres de session Divers Pour forcer un alignement différent Par défaut, une session ...",""],
["./sessiondirsyncnamefilter.html","Paramètres de filtre de nom de la Synchronisation de Dossiers","Paramètres de filtre de nom de la Synchronisation de Dossiers Session Paramètres de session Filtres sur le nom Vous pouvez inclure ou exclure des ...",""],
["./sessiondirsyncops.html","Paramètres de synchronisation de Synchronisation de Dossiers","Paramètres de synchronisation de Synchronisation de Dossiers Session Paramètres de session Synchroniser Opérations Prédéfinitions Vous pouvez util...",""],
["./sessiondirsyncotherfilters.html","Paramètres des autres filtres de la Synchronisation de Dossiers","Paramètres des autres filtres de la Synchronisation de Dossiers Session Paramètres de session Autres filtres Vous pouvez exclure des fichiers d&#39;un...",""],
["./sessiondirsyncspecs.html","Paramètres de spécification d&#39;une Synchronisation de Dossiers","Paramètres de spécification d&#39;une Synchronisation de Dossiers Session Paramètres de session Spécification Spécifiez les dossiers de base à synchro...",""],
["./sessionhex.html","Paramètres de Comparaison Hexadécimale","Paramètres de Comparaison Hexadécimale Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spéc...",""],
["./sessionhexcomparison.html","Paramètres de comparaison de Comparaison Hexadécimale","Paramètres de comparaison de Comparaison Hexadécimale Session Paramètres de session Comparaison Ces paramètres contrôlent comment les fichiers son...",""],
["./sessionhexformats.html","Paramètres de format de fichier de Comparaison Hexadécimale","Paramètres de format de fichier de Comparaison Hexadécimale Session Paramètres de session Format Spécifiez le format de fichier à utiliser en lisa...",""],
["./sessionhexspecs.html","Paramètres de spécification d&#39;une Comparaison Hexadécimale","Paramètres de spécification d&#39;une Comparaison Hexadécimale Session Paramètres de session Spécification Spécifiez les fichiers à comparer. Cochez D...",""],
["./sessionmp3.html","Paramètres de Comparaison de MP3","Paramètres de Comparaison de MP3 Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spécificat...",""],
["./sessionmp3importance.html","Paramètres d&#39;importance de Comparaison de MP3","Paramètres d&#39;importance de Comparaison de MP3 Session Paramètres de session Importance Ces paramètres contrôlent quelles différences doivent être ...",""],
["./sessionmp3specs.html","Paramètres de spécification d&#39;une Comparaison de MP3","Paramètres de spécification d&#39;une Comparaison de MP3 Session Paramètres de session Spécification Spécifiez les fichiers à comparer. La Description...",""],
["./sessionpix.html","Paramètres de Comparaison d&#39;Images","Paramètres de Comparaison d&#39;Images Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spécific...",""],
["./sessionpixformats.html","Paramètres de format de fichier de Comparaison d&#39;Images","Paramètres de format de fichier de Comparaison d&#39;Images Session Paramètres de session Format Spécifiez le format de fichier à utiliser en lisant l...",""],
["./sessionpixreplacements.html","Paramètres de remplacement de Comparaison d&#39;Images","Paramètres de remplacement de Comparaison d&#39;Images Session Paramètres de session Remplacements Remplacements identifient des changements qui devra...",""],
["./sessionpixspecs.html","Paramètres de spécification d&#39;une Comparaison d&#39;Images","Paramètres de spécification d&#39;une Comparaison d&#39;Images Session Paramètres de session Spécification Spécifiez les fichiers à comparer. La Descripti...",""],
["./sessionreg.html","Paramètres de Comparaison de Registres","Paramètres de Comparaison de Registres Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spéc...",""],
["./sessionregspecs.html","Paramètres de spécification d&#39;une Comparaison de Registres","Paramètres de spécification d&#39;une Comparaison de Registres Session Paramètres de session Spécification Spécifiez les fichiers à comparer. La Descr...",""],
["./sessiontext.html","Paramètres de Comparaison de Textes","Paramètres de Comparaison de Textes Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spécifi...",""],
["./sessiontextalignment.html","Paramètres d&#39;alignement de Comparaison de Textes","Paramètres d&#39;alignement de Comparaison de Textes Session Paramètres de session Alignement Les paramètres de l&#39;onglet Alignement contrôle l&#39;algorit...",""],
["./sessiontextformats.html","Paramètres de format de fichier de Comparaison de Textes","Paramètres de format de fichier de Comparaison de Textes Session Paramètres de session Format Spécifiez le format de fichier à utiliser en lisant ...",""],
["./sessiontextimportance.html","Paramètres d&#39;importance de Comparaison de Textes","Paramètres d&#39;importance de Comparaison de Textes Session Paramètres de session Importance Ces paramètres contrôlent quelles sont les différences q...",""],
["./sessiontextmerge.html","Paramètres de Fusion de Textes","Paramètres de Fusion de Textes Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spécificatio...",""],
["./sessiontextmergealignment.html","Paramètres d&#39;alignement de la Fusion de Textes","Paramètres d&#39;alignement de la Fusion de Textes Session Paramètres de session Alignement Les paramètres de l&#39;onglet Alignement contrôle l&#39;algorithm...",""],
["./sessiontextmergeformats.html","Paramètres de formats de fichier de la Fusion de Textes","Paramètres de formats de fichier de la Fusion de Textes Session Paramètres de session Format Spécifiez le format de fichier à utiliser en lisant l...",""],
["./sessiontextmergeimportance.html","Paramètres d&#39;importance de la Fusion de Textes","Paramètres d&#39;importance de la Fusion de Textes Session Paramètres de session Importance Ces paramètres contrôlent quelles sont les différences que...",""],
["./sessiontextmergespecs.html","Paramètres de spécification d&#39;une Fusion de Textes","Paramètres de spécification d&#39;une Fusion de Textes Session Paramètres de session Spécification Spécifiez les fichiers à fusionner. Fusionner vers ...",""],
["./sessiontextreplacements.html","Paramètres de remplacement de Comparaison de Textes","Paramètres de remplacement de Comparaison de Textes Session Paramètres de session Remplacements Remplacements identifient des changements répétiti...",""],
["./sessiontextspecs.html","Paramètres de spécification d&#39;une Comparaison de Textes","Paramètres de spécification d&#39;une Comparaison de Textes Session Paramètres de session Spécification Spécifiez les fichiers à comparer. Cochez Désa...",""],
["./sessionver.html","Paramètres de Comparaison de Versions","Paramètres de Comparaison de Versions Session Paramètres de session Cliquez sur l&#39;onglet contenant les paramètres que vous voulez modifier : Spéci...",""],
["./sessionverimportance.html","Paramètres d&#39;importance de Comparaison de Versions","Paramètres d&#39;importance de Comparaison de Versions Session Paramètres de session Importance Ces paramètres contrôlent quelles différences doivent ...",""],
["./sessionverspecs.html","Paramètres de spécification d&#39;une Comparaison de Versions","Paramètres de spécification d&#39;une Comparaison de Versions Session Paramètres de session Spécification Spécifiez les fichiers à comparer. La Descri...",""],
["./session_settings.html","Paramètres de session","Paramètres de session Pour modifier les paramètres de session 1.Sélectionnez Session Paramètres de session . 2.Modifiez les paramètres souhaités d...",""],
["./settings_reference.html","Référence des paramètres","Référence des paramètres Beyond Compare est hautement configurable et il peut être parfois difficile de savoir où aller dans le programme pour mod...",""],
["./sharing_sessions.html","Partage de sessions","Partage de sessions Plusieurs utilisateurs peuvent partager des sessions en utilisant un fichier de sessions partagées. Pour créer un fichier de s...",""],
["./snapshots.html","Instantanés","Instantanés Dans le menu Outils, la commande Enregistrer un Instantané enregistre une liste compressée en lecture seule du dossier spécifié et de ...",""],
["./specs.html","Spécification","Spécification Une Spécification est le nom d&#39;un dossier ou d&#39;un fichier. Beyond Compare supporte plusieurs types différents de spécifications. Les...",""],
["./standard_vs_pro.html","Éditions Standard vs Pro","Éditions Standard vs Pro L&#39;édition Standard de Beyond Compare est un outil de comparaison avec des fonctionnalités complètes, pas une version rédu...",""],
["./support_ordering_and_license.html","Support, commande et licence","Support, commande et licence Pour la dernière version de Beyond Compare et pour d&#39;autres nouvelles concernant le programme, visitez notre site web...",""],
["./using_bc.html","Utiliser Beyond Compare","Utiliser Beyond Compare Beyond Compare traite une grande variété de tâches de comparaison. Il possède des vues spécialisés pour des fichiers de ty...",""],
["./using_text_merge.html","Utiliser la Fusion de Textes","Utiliser la Fusion de Textes Une fois que Beyond Compare a terminé la comparaison, il affichera jusqu&#39;à quatre panneaux : Les panneaux gauche, cen...",""],
["./viewdata.html","Vue d&#39;ensemble de la Comparaison de Tableaux","Vue d&#39;ensemble de la Comparaison de Tableaux Une session de Comparaison de Tableaux compare des fichiers texte contenant des données tabulaires te...",""],
["./viewdir.html","Vue d&#39;ensemble de la Comparaison de Dossiers","Vue d&#39;ensemble de la Comparaison de Dossiers Une session de Comparaison de Dossiers compare deux structures de dossiers côte à côte, similairement...",""],
["./viewdirmerge.html","Vue d&#39;ensemble de la Fusion de Dossiers","Vue d&#39;ensemble de la Fusion de Dossiers Une session de Fusion de Dossiers affiche deux ou trois structures de dossiers côte à côte. Les panneaux g...",""],
["./viewdirsync.html","Vue d&#39;ensemble de la Synchronisation de Dossiers","Vue d&#39;ensemble de la Synchronisation de Dossiers Une session de Synchronisation de Dossiers est une session spécialisée de dossiers qui synchronis...",""],
["./viewhex.html","Vue d&#39;ensemble de la Comparaison Hexadécimale","Vue d&#39;ensemble de la Comparaison Hexadécimale Une session de Comparaison Hexadécimale compare visuellement le contenu brut de deux fichiers, avec ...",""],
["./viewhome.html","Vue Accueil","Vue d&#39;ensemble de la page d&#39;accueil Lorsque vous ouvrez une nouvelle fenêtre ou onglet, Beyond Compare affiche la vue Accueil : Depuis la vue Accu...",""],
["./viewother.html","Autres types de vue","Autres types de vue Comparaison de MP3 Une session de Comparaison de MP3 compare deux fichiers MP3 en mettant en surbrillance les différences des ...",""],
["./viewpix.html","Vue d&#39;ensemble de la Comparaison d&#39;Images","Vue d&#39;ensemble de la Comparaison d&#39;Images Une session de Comparaison d&#39;Images compare un couple d&#39;images visuellement, montrant les différences en...",""],
["./viewreg.html","Vue d&#39;ensemble de la Comparaison de Registres","Vue d&#39;ensemble de la Comparaison de Registres Une session de Comparaison de Registres compare des registres actifs de votre ordinateur ou sur d&#39;au...",""],
["./viewtext.html","Vue d&#39;ensemble de la Comparaison de Textes","Vue d&#39;ensemble de la Comparaison de Textes Une session de Comparaison de Textes compare visuellement deux fichiers texte dans une disposition côte...",""],
["./viewtextedit.html","Vue d&#39;ensemble de la modification de texte","Vue d&#39;ensemble de la modification de texte Une vue Éditeur de texte est un éditeur de texte dans un panneau simple. Voir également Commandes d&#39;Édi...",""],
["./viewtextmerge.html","Vue d&#39;ensemble de la Fusion de Textes","Vue d&#39;ensemble de la Fusion de Textes Une session de Fusion de Textes contient deux ou trois panneaux source non modifiables et un panneau de sort...",""],
["./viewtextpatch.html","Vue d&#39;ensemble de patch texte","Vue d&#39;ensemble de patch texte Une vue de Patch de texte recrée une comparaison représentée dans un fichier patch. Les fichiers patch peuvent être ...",""],
["./walking_through_differences.html","Parcourir les différences","Parcourir les différences Dans le menu Recherche, les commandes Section de différences suivante et Section de différences précédente vous aident à...",""],
["./welcome.html","Bienvenue","Bienvenue dans Beyond Compare 4 Beyond Compare est un utilitaire de comparaison de fichiers et de dossiers. Il peut vous aider à faire correspondr...",""],
["./whats_new.html","Quoi de neuf ?","Quoi de neuf ? Voici quelques-unes des nouvelles fonctionnalités significatives de Beyond Compare 4. Les éléments marqués avec ne sont valides que...",""],
["./where_settings_are_stored.html","Où sont enregistrés les paramètres sur votre ordinateur","Où sont enregistrés les paramètres sur votre ordinateur Beyond Compare mémorise vos sessions, formats personnalisés de fichier et autres préférenc...",""]];
